#include <iostream>
#include <exception>
using namespace std;

int main2() {
	cout << "xd";
	return 0;
}